[package]
name = "pct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
serde = "1.0.193"
serde_derive = "1.0.193"
serde_json = "1.0.108"
